### ISSUE TITLE
Can you also update the game patches for canary?

### ISSUE THREAD

**Issue by tliron** [Chopper1337/XeniaUpdater#7]
Thank you so much for this little program. :)

My feature request is that you add support for downloading and updating the [patches for canary](https://github.com/xenia-canary/game-patches).

**Comment by Chopper1337** [comment]
It seems like it could be done, I'll look into it

**Comment by Chopper1337** [comment]
Try this out: https://github.com/Chopper1337/XeniaUpdater2/releases/tag/1.0
Feedback is appreciated :)

**Comment by tliron** [comment]
Seems to work, thank you! :)
